# Generated by Django 3.1.7 on 2021-03-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0002_recruiter_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiter',
            old_name='compnay_name',
            new_name='company',
        ),
    ]
